### ISSUE TITLE
Next JS server phase II

### ISSUE THREAD

**Issue by pmi** [enonic/nextjs-demo#112]
### Individual parts queries

- [x] #123
- [x] #124
- [x] #126
- [x] #127
- [x] #129

### Catch-all for easy mapping and turning on/off the default rendering

- [x] #113
- [x] #114
- [x] #115

### Error handling

- [x] #151
- [ ] #153
- [ ] #155

### Existing components

-  [x] #116
-  [x] #144
-  [ ] Getting custom config for part components
-  [ ] Move comp registration to their files

### Layout

- [x] #118
- [x] #119

### Fragment

- [x] #132
- [x] #138
- [x] #139
- [x] #141

### Page Templates

- [x] #142
- [ ] #156

### Macros

- [ ] Macro support

### Proxy lib

- [x] Rename the lib-nextjs-proxy (and therefore rename the mapping to /__nextproxy__/ too)
- [x] #120
- [x] #148
- [ ] Remove workarounds for 7.7

**Comment by espen42** [comment]
Suggestions:
Catch-all for easy mapping and turning on/off the default rendering:
 Let the mapped catch-all renderer be sensitive to next runtime mode - data dump in dev, empty (or simple name-placeholder marker?) in prod

**Comment by pmi** [comment]
> Rename the page controller: next-js-renderer.js or just next-js.js
I think it's too early to form the sample app yet if that's what you mean because we even don't have an enonic repo for that ;)
